export const userType = {
  REGISTER_USER: 'REGISTER_USER',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  GET_ME: 'GET_ME',
  GET_QRCODE: 'GET_QRCODE',
  TOGGLE_MFA: 'TOGGLE_MFA',
  VERIFY_MFA: 'VERIFY_MFA',
  SEND_VERIFY_EMAIL: 'SEND_VERIFY_EMAIL',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
};
